CREATE TABLE IF NOT EXISTS driver_availability (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  driver_user_id VARCHAR(255) NOT NULL,
  driver_name VARCHAR(255) NULL,
  phone_number VARCHAR(80) NULL,
  vehicle_tier_key VARCHAR(80) NULL,
  vehicle_tier_name VARCHAR(120) NULL,
  vehicle_make VARCHAR(120) NULL,
  vehicle_model VARCHAR(120) NULL,
  number_plate VARCHAR(80) NULL,
  car_photo_url TEXT NULL,
  current_lat DECIMAL(10,7) NULL,
  current_lng DECIMAL(10,7) NULL,
  is_online TINYINT(1) NOT NULL DEFAULT 0,
  last_seen_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_driver_availability_user (driver_user_id),
  INDEX idx_driver_availability_online (is_online, vehicle_tier_key),
  INDEX idx_driver_availability_coords (current_lat, current_lng)
);

CREATE TABLE IF NOT EXISTS ride_requests (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL,
  passenger_user_id VARCHAR(255) NOT NULL,
  passenger_name VARCHAR(255) NULL,
  passenger_phone VARCHAR(80) NULL,
  driver_user_id VARCHAR(255) NULL,
  driver_name VARCHAR(255) NULL,
  driver_phone VARCHAR(80) NULL,
  requested_tier_key VARCHAR(80) NOT NULL,
  requested_tier_name VARCHAR(120) NOT NULL,
  pickup_label VARCHAR(255) NOT NULL,
  pickup_lat DECIMAL(10,7) NOT NULL,
  pickup_lng DECIMAL(10,7) NOT NULL,
  dropoff_label VARCHAR(255) NOT NULL,
  dropoff_lat DECIMAL(10,7) NOT NULL,
  dropoff_lng DECIMAL(10,7) NOT NULL,
  estimated_distance_km DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  estimated_minutes INT NOT NULL DEFAULT 0,
  estimated_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  driver_distance_km DECIMAL(10,2) NULL,
  driver_eta_minutes INT NULL,
  status ENUM('requested', 'driver_found', 'driver_assigned', 'driver_arrived', 'in_progress', 'completed', 'cancelled', 'expired') NOT NULL DEFAULT 'requested',
  cancellation_reason VARCHAR(255) NULL,
  requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  driver_found_at TIMESTAMP NULL DEFAULT NULL,
  assigned_at TIMESTAMP NULL DEFAULT NULL,
  arrived_at TIMESTAMP NULL DEFAULT NULL,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  cancelled_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ride_requests_public_id (public_id),
  INDEX idx_ride_requests_passenger (passenger_user_id, requested_at),
  INDEX idx_ride_requests_driver (driver_user_id, requested_at),
  INDEX idx_ride_requests_status (status, requested_at),
  INDEX idx_ride_requests_requested_tier (requested_tier_key)
);
