CREATE TABLE IF NOT EXISTS ride_panic_alerts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ride_request_id BIGINT UNSIGNED NOT NULL,
  ride_public_id VARCHAR(64) NULL,
  actor_role ENUM('passenger', 'driver') NOT NULL,
  actor_user_id VARCHAR(128) NOT NULL,
  actor_name VARCHAR(255) NULL,
  passenger_user_id VARCHAR(128) NOT NULL,
  passenger_name VARCHAR(255) NULL,
  driver_user_id VARCHAR(128) NULL,
  driver_name VARCHAR(255) NULL,
  ride_status VARCHAR(64) NOT NULL,
  alert_stage VARCHAR(64) NULL,
  message TEXT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  status ENUM('open', 'reviewed', 'resolved') NOT NULL DEFAULT 'open',
  admin_note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_ride_panic_alerts_ride_request_id (ride_request_id),
  KEY idx_ride_panic_alerts_actor_user_id (actor_user_id),
  KEY idx_ride_panic_alerts_passenger_user_id (passenger_user_id),
  KEY idx_ride_panic_alerts_driver_user_id (driver_user_id),
  KEY idx_ride_panic_alerts_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
