CREATE TABLE IF NOT EXISTS place_search_cache (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  provider VARCHAR(32) NOT NULL,
  provider_place_id VARCHAR(191) NULL,
  provider_place_key VARCHAR(191) NOT NULL,
  normalized_query VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255) NULL,
  display_name VARCHAR(500) NOT NULL,
  search_text TEXT NOT NULL,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  district VARCHAR(255) NULL,
  city VARCHAR(255) NULL,
  region VARCHAR(255) NULL,
  country VARCHAR(120) NULL,
  raw_payload_json LONGTEXT NULL,
  usage_count INT NOT NULL DEFAULT 0,
  last_used_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_place_search_cache_provider_place_key (provider_place_key),
  KEY idx_place_search_cache_normalized_query (normalized_query),
  KEY idx_place_search_cache_last_used_at (last_used_at)
)
