CREATE TABLE IF NOT EXISTS driver_income_goals (
  driver_user_id VARCHAR(255) NOT NULL PRIMARY KEY,
  daily_goal_amount DECIMAL(12,2) NOT NULL DEFAULT 50.00,
  currency VARCHAR(8) NOT NULL DEFAULT 'USD',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
