CREATE TABLE IF NOT EXISTS hire_vehicles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(32) NOT NULL,
  driver_user_id VARCHAR(255) NOT NULL,
  title VARCHAR(160) NOT NULL,
  category VARCHAR(64) NOT NULL DEFAULT 'sedan',
  make VARCHAR(80) NULL DEFAULT NULL,
  model VARCHAR(80) NULL DEFAULT NULL,
  year INT NULL DEFAULT NULL,
  color VARCHAR(40) NULL DEFAULT NULL,
  number_plate VARCHAR(32) NULL DEFAULT NULL,
  seat_count INT NULL DEFAULT NULL,
  description TEXT NULL,
  daily_rate DECIMAL(12, 2) NULL DEFAULT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'USD',
  photo_urls JSON NULL,
  vehicle_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  rejection_reason TEXT NULL,
  submitted_at DATETIME NULL DEFAULT NULL,
  reviewed_at DATETIME NULL DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_hire_vehicles_public_id (public_id),
  KEY idx_hire_vehicles_driver (driver_user_id),
  KEY idx_hire_vehicles_status (vehicle_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hire_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(32) NOT NULL,
  passenger_user_id VARCHAR(255) NOT NULL,
  category VARCHAR(64) NULL DEFAULT NULL,
  pickup_label VARCHAR(255) NOT NULL,
  pickup_lat DECIMAL(10, 7) NULL DEFAULT NULL,
  pickup_lng DECIMAL(10, 7) NULL DEFAULT NULL,
  dropoff_label VARCHAR(255) NULL DEFAULT NULL,
  dropoff_lat DECIMAL(10, 7) NULL DEFAULT NULL,
  dropoff_lng DECIMAL(10, 7) NULL DEFAULT NULL,
  start_at DATETIME NOT NULL,
  end_at DATETIME NULL DEFAULT NULL,
  passenger_count INT NOT NULL DEFAULT 1,
  notes TEXT NULL,
  status ENUM('open', 'quoted', 'booked', 'cancelled', 'expired') NOT NULL DEFAULT 'open',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  cancelled_at DATETIME NULL DEFAULT NULL,
  UNIQUE KEY uniq_hire_requests_public_id (public_id),
  KEY idx_hire_requests_passenger (passenger_user_id),
  KEY idx_hire_requests_status (status),
  KEY idx_hire_requests_start (start_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hire_quotes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(32) NOT NULL,
  hire_request_id BIGINT UNSIGNED NOT NULL,
  driver_user_id VARCHAR(255) NOT NULL,
  hire_vehicle_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'USD',
  message VARCHAR(500) NULL DEFAULT NULL,
  status ENUM('pending', 'accepted', 'declined', 'withdrawn', 'expired') NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_hire_quotes_public_id (public_id),
  UNIQUE KEY uniq_hire_quotes_request_driver (hire_request_id, driver_user_id),
  KEY idx_hire_quotes_driver (driver_user_id),
  KEY idx_hire_quotes_vehicle (hire_vehicle_id),
  KEY idx_hire_quotes_status (status),
  CONSTRAINT fk_hire_quotes_request FOREIGN KEY (hire_request_id) REFERENCES hire_requests(id) ON DELETE CASCADE,
  CONSTRAINT fk_hire_quotes_vehicle FOREIGN KEY (hire_vehicle_id) REFERENCES hire_vehicles(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hire_bookings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(32) NOT NULL,
  hire_request_id BIGINT UNSIGNED NOT NULL,
  hire_quote_id BIGINT UNSIGNED NOT NULL,
  hire_vehicle_id BIGINT UNSIGNED NOT NULL,
  passenger_user_id VARCHAR(255) NOT NULL,
  driver_user_id VARCHAR(255) NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'USD',
  status ENUM('confirmed', 'in_progress', 'completed', 'cancelled') NOT NULL DEFAULT 'confirmed',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  started_at DATETIME NULL DEFAULT NULL,
  completed_at DATETIME NULL DEFAULT NULL,
  cancelled_at DATETIME NULL DEFAULT NULL,
  UNIQUE KEY uniq_hire_bookings_public_id (public_id),
  UNIQUE KEY uniq_hire_bookings_request (hire_request_id),
  KEY idx_hire_bookings_passenger (passenger_user_id),
  KEY idx_hire_bookings_driver (driver_user_id),
  KEY idx_hire_bookings_status (status),
  CONSTRAINT fk_hire_bookings_request FOREIGN KEY (hire_request_id) REFERENCES hire_requests(id) ON DELETE RESTRICT,
  CONSTRAINT fk_hire_bookings_quote FOREIGN KEY (hire_quote_id) REFERENCES hire_quotes(id) ON DELETE RESTRICT,
  CONSTRAINT fk_hire_bookings_vehicle FOREIGN KEY (hire_vehicle_id) REFERENCES hire_vehicles(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
